### ISSUE TITLE
Get git context from the underlying Git repository

### ISSUE THREAD

**Issue by mdelapenya** [mdelapenya/junit2otlp#10]
We'd like to get the following information from the underlying git repository (including potential keys), to correlate test execution with authors/committers:

## General SCM attributes
| Description | Attribute key | Type | Description |
| - | - | - | - |
| Repository Type | `scm.type` | string | i.e. `git`, `svn`... |
| Git repository | `scm.repository` | string | i.e. https://github.com/elastic/beats.git |
| Current branch name | `scm.branch` | string | i.e. main, `feature/23-fix`, `merge_requests/23` |
| Target branch (if a PR) | `scm.branch.target` | string | If not a pull/merge request, the field should not be added |
| List of authors in the branch | `scm.authors` | array| Array of `scm.username` |
| Added lines | `scm.lines.added` | int | Only for pull requests |
| Deleted lines | `scm.lines.deleted` | int | Only for pull requests |

### Git specific attributes
| Description | Attribute key | Type | Description |
| - | - | - | - |
| List of committers in the branch | `git.committers` | array | Array of `git.username`. Not using `scm` as I'm not sure if other SCMs have the ability of committing on behalf others  |
| Clone depth | `git.clone.depth` | long |  |
| Is shallow clone | `git.clone.shallow` | bool |  |

@v1v @kuisathaverat @cyrille-leclerc thoughts?

**Comment by cyrille-leclerc** [comment]
Here is what we already capture:
https://github.com/jenkinsci/opentelemetry-plugin/blob/opentelemetry-0.22-beta-4/src/main/java/io/jenkins/plugins/opentelemetry/semconv/JenkinsOtelSemanticAttributes.java#L45-L49
* String git.repository
* String git.branch
* String git.username
* Long git.clone.depth
* Boolean git.clone.shallow

Few comments:
* You probably want to also capture "git.repository"
* We are misaligned on Jenkins' "git.branch" versus your "git.branch.name"
* "git.branch.target" sounds to me like ~"git.pr.targetBranch" (name to define), do we use "PR" or "MR"...

**Comment by v1v** [comment]
After reading this I wonder if the attributes should be git prefix agnostic and scm prefix based. And create a new attribute called `scm.type` = ( git or svn or accurev or cvs or any other type).

**Comment by mdelapenya** [comment]
> After reading this I wonder if the attributes should be git prefix agnostic and scm prefix based. And create a new attribute called `scm.type` = ( git or svn or accurev or cvs or any other type).

I like it, although there will be attributes specific to git, like `git.clone.shallow`. Nevertheless, +1 to adding a `scm.type` attribute

**Comment by mdelapenya** [comment]
Besides that, I think we should go step by step, implementing this for git as it's practically mainstream in the dev community. We can evaluate supporting other SCMs depending on the usage, although I'd say that Git is ubiquitous over any other: svn, mercurial, plastic...

**Comment by mdelapenya** [comment]
> * "git.branch.target" sounds to me like ~"git.pr.targetBranch" (name to define), do we use "PR" or "MR"...

Because a PR/MR is a branch, we can fill in the `git.branch.target` attribute if and only if the branch represents a pull/merge request.

**Comment by cyrille-leclerc** [comment]
> After reading this I wonder if the attributes should be git prefix agnostic and scm prefix based. And create a new attribute called `scm.type` = ( git or svn or accurev or cvs or any other type).

I would not be afraid of optimizing for Git for the moment as it's the de facto standard and I don't see it contested in the coming years.

**Comment by mdelapenya** [comment]
I updated the keys in the description 🤞

**Comment by cyrille-leclerc** [comment]
`scm.lines.added` and `scm.lines.deleted` sound weird to me because lines added and deleted are not generic to an scm but are specific to a diff between to states (ie 2 branches or 2 states of files)

**Comment by mdelapenya** [comment]
> * `scm.lines.added` and `scm.lines.deleted` sound weird to me because lines added and deleted are not generic to an scm but are specific to a diff between to states (ie 2 branches or 2 states of files)

This is a metric obtained from pull/merge requests, only.

> * `scm.repository` being `elastic/beats` sounds incomplete to me because we need the SCM server url or something like this.
Indeed. Will update to the complete URL, including protocol

**Comment by mdelapenya** [comment]
I think we can close this one, as it's already implemented. We are in the process of renaming the attributes, following a proper name convention
